language: go
go:
- 1.7.4
go_import_path: v2ray.com/core
git:
  depth: 5
script:
- go test -tags json v2ray.com/core/...
after_success:
- ./testing/coverage/coverall
before_deploy:
- ./tools/release/release-ci.sh
- gem install octokit -v 4.3.0
deploy:
  provider: releases
  api_key:
    secure: h7P6y7jHe0yALKgXb9HyPAlE6JPOB/BiScMlqsG6MUF0G29JrEjcDXh/jZm8HB82OfUG3zPBtr5m0P3LUoM60EQQ96/yE9KKrhEBeyF+E9CAOUHx7Ar4XDR7dG7/Wv+q3ZRFl+4CB5f7xbt9qlobqXkeffngeu9RNWngqVvbyTWIZclx7NYl5haf/hhqGcX2OPKQQfjvOsnP+uLmqiRJBbaYQMzPmvjaQJ9cB6Z11ctJqunk3bN89nV86uaHLqmz8nfk3/J7RjdeT0mqgRYVwfMavZifGPISlgsZd7N0PqiiWB7gZqzjbiSCur+PtnVScYfTlfNoRP+XJtVx3OFnepffSvyE6zOP20MEINAMOgME68Zzkaab8JnDVwj0eTsPNEDpK+E+RUZ1IkaAvVZ19L0qNYwO6bP8koUI4cFDI45srcx0o5xC7Hzz1eaSm5ZJZ3iwwzFZE2vFm83pcQilopG0E7gTYyB+fk0x6sca5MY1PhHAByvBbvYhsCBV4x4o0N1lD1V3QXhvljJL4qieFybwg8g0hdUNeSrm2+NxPqKpEHUQWQFGsl0OGMy2Ji6u/NG5tSvfWKUUsXpkueyutvfTb9D94Xk4s1eNGMG+BHFIGHRTZzX6XXB7/j3zObWApD3h8SIbXjfL0mLaKaBeMyLwf2tlsKTgzwEjvIzcNfQ=
  file:
  - $GOPATH/bin/v2ray-macos.zip
  - $GOPATH/bin/v2ray-windows-64.zip
  - $GOPATH/bin/v2ray-windows-32.zip
  - $GOPATH/bin/v2ray-linux-64.zip
  - $GOPATH/bin/v2ray-linux-32.zip
  - $GOPATH/bin/v2ray-linux-arm.zip
  - $GOPATH/bin/v2ray-linux-arm64.zip
  - $GOPATH/bin/v2ray-linux-mips64.zip
  - $GOPATH/bin/v2ray-freebsd-64.zip
  - $GOPATH/bin/v2ray-freebsd-32.zip
  - $GOPATH/bin/v2ray-openbsd-64.zip
  - $GOPATH/bin/v2ray-openbsd-32.zip
  - $GOPATH/bin/metadata.txt
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: GQrOIEosXGR8NXQVeRmNuyz0TSDPyq0UHtpObhA0ZKHvhO4eNWUVRTwF/V1vrcNxMDcNQBeTVHIdWJYTaq8iG0qtEPiCCt3wVqX8jRssRNjw7dY1a/LK7Jj1c3py7vZPWnEC+i4x0sJJLeDTnY/f+YaScAnEQrVwEaRSH3A0TDMPMG7/7UJVfPtFYkqt3BSDGSBOgKsh9IJzaZ6zFARiQJLxuGz9pEpKwgWlErKwcs5JuHxXBdLXh84DE7kBmMi5j5zdp9O77Ed+bjZ2MZ3WHLSZyab2OlJICt8Wy0b8dzvqefek0t9TTu1M+GxtQjPfr//cToK0wzOQSOKX5hSUcygGJB7xcTs4xzArDWtDBBsiX/v1s965enODEjhqyvb2yGl5VrlN2SEOHAXsLgnlY+0NMieeY0i1GA/d0pgoRmQphfXuoaVVRlCFQT85lF62ieg1Uzob8hra2jAkumrsOcFZyYbDFQdWwqswbz2Z+S79YBmcdYucHqYuGwYQuZEmasv0p8F/LF0hQ8VaY57lZ3OIfegM+hIo9yf/wlTgnXt2UWe0U1ktQcjz6O6obVu0vnV/Q5LzIjhB++agABdk/kzM+m2+79+59IqEyymiMH38kXDOU7YCxAQkQDzsP662MEVdbst8/IpWhHwhys8ezdsKM98vg3uLd391E8vwhKI=
  - secure: i+BVZ0oC1YnQb/2EprCFlQh3uzO2Kwu0LSyelFF0mfsIR7nSbVEP1T5gvBxyM8ZsuTfGW+70FLdfvntkwXXJ7sQm5bJlKlIQa0G5eC8G6dqpGknEgX5PZ1h+BoGkhZHDp12T0bJF3McoECMERAV/R6uFqn5LlTO5M0LSTmeqQRPlaRQnt4Qh0PD3REHCY4MrNZZuhUOxOA6cttJwUUtr6ECTSfRYxK7Dg2s/dUeBrfbPOvNhQkPbosv5Wft3S5+WYtin/4DRZO/T1Gd2WsOdEL8BqqXAfA1s4qW+U0zmp+vIG2hTlKS1fHWEfM9bpqShHSO/DKqPbwI0v8dIkTbEShOrF/+aZ2HnWSMbyXJBjtVKh2h8uDLqHCRuVXuQix2cS/5+RRj8vPoAWIa09Z60g4SrtJe1BKTPj3PLXlcN8KRIIXaJq9Lh+SDqxlWsK2m18AYVtAwkAAdyDPHOi0wy79mF1sSweD3/um+S+pmgOlmRoYOpXb17SR6RkOgETEzeihrG0Qmrlvsgp94IswDN+AvVFp17w3wFVd+tApHYTXoxuEl8qoqsNBtAE778hgrUt1cwaWM3Vw5x3EuXWYYxMjlNNC5lURpBL6jlStPFTrE4UnK5KEyIE7GZQOeJV9SplxYGUvagerv1mREtYob6S1hcOedyUAo6EIsAzJ8l4Ek=
